### ISSUE TITLE
[#63-BG]User can't log out

### ISSUE THREAD

**Issue by somnus0x** [whsatku/social#63]

**Comment by whs** [comment]
Should be fixed in ff56da364fc1e64fe820d9c29d5df1c9eacfde46

**Comment by vasupol11** [comment]
I still cant logout master branch. What do you think is the cause??
